using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
using UnityEngine.EventSystems;
using System;

public class LinkHandler : MonoBehaviour
{
    
    [SerializeField]private TMP_Text _tmpTextBox;
    private Canvas _canvasToCheck;
    [SerializeField] private Camera cameraToUse;
    private int currentHoveredLinkIndex = -1;
    
    void Awake()
    {
        _canvasToCheck = GetComponentInParent<Canvas>();

        if(_canvasToCheck.renderMode == RenderMode.ScreenSpaceOverlay){
            cameraToUse = null;
        }

        if(cameraToUse == null){
            cameraToUse = Camera.main;
        }
    }
    
    void Start()
    {
        // å¼ºåˆ¶æ›´æ–°æ–‡æœ¬ä»¥ç¡®ä¿linkInfoè¢«æ­£ç¡®ç”Ÿæˆ
        _tmpTextBox.ForceMeshUpdate();
    }
    
    void Update()
    {
        // æŒç»­æ£€æµ‹é¼ æ ‡æ‚¬åœ
        CheckMouseOverLink();
    }
    
    private void CheckMouseOverLink()
    {
        Vector3 mousePosition = Input.mousePosition;
        
        // ä½¿ç”¨æ”¹è¿›çš„é“¾æ¥æ£€æµ‹æ–¹æ³•
        var linkTaggedText = FindLinkAtMousePosition(mousePosition);
        
        if(linkTaggedText != -1 && linkTaggedText != currentHoveredLinkIndex){
            currentHoveredLinkIndex = linkTaggedText;
            TMP_LinkInfo linkInfo = _tmpTextBox.textInfo.linkInfo[linkTaggedText];
            string linkText = linkInfo.GetLinkText();
            Debug.Log("ğŸ” æ‚¬åœåˆ°é“¾æ¥: " + linkText);

            EnterLink(linkText);

        }
        else if(linkTaggedText == -1 && currentHoveredLinkIndex != -1){
            Debug.Log("ğŸ‘‹ ç¦»å¼€é“¾æ¥");
            currentHoveredLinkIndex = -1;

            ExitLink();
        }
    }
    
    private int FindLinkAtMousePosition(Vector3 mousePosition)
    {
        // ScreenSpaceOverlayæ¨¡å¼ä¸‹ä½¿ç”¨nullæ‘„åƒæœºå‚æ•°
        if (_canvasToCheck.renderMode == RenderMode.ScreenSpaceOverlay)
        {
            return TMP_TextUtilities.FindIntersectingLink(_tmpTextBox, mousePosition, null);
        }
        
        // å…¶ä»–æ¨¡å¼ä½¿ç”¨åŸå§‹æ–¹æ³•
        return TMP_TextUtilities.FindIntersectingLink(_tmpTextBox, mousePosition, cameraToUse);
    }

    void EnterLink(string linkText){
        // HoverInfoController.Instance.MouseEnterKeyWord(linkText,this);
    }

    void ExitLink(){
        // HoverInfoController.Instance.MouseExitKeyWord(this);
    }
}
